/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import static io.javalin.testtools.JavalinTest.test;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import hexlet.code.repository.UrlRepository;
import org.junit.jupiter.api.Test;

class AppTest {
    private static final String DEFAULT_DATABASE_URL = "jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;";

    @Test
    void appCanBeCreated() throws Exception {
        var app = App.getApp();

        assertNotNull(app);
    }

    @Test
    void rootRouteReturnsMainPage() throws Exception {
        test(App.getApp(), (server, client) -> {
            var response = client.get("/");
            var body = response.body().string();

            assertEquals(200, response.code());
            assertTrue(body.contains("Анализатор страниц"));
            assertTrue(body.contains("Бесплатно проверяйте сайты на SEO пригодность"));
            assertTrue(body.contains("action=\"/urls\""));
            assertTrue(body.contains("https://www.example.com"));
        });
    }

    @Test
    void defaultPortIsUsed() {
        assertEquals(7070, App.getPort(null));
    }

    @Test
    void portCanBeConfigured() {
        assertEquals(5000, App.getPort("5000"));
    }

    @Test
    void environmentPortIsUsed() {
        var port = System.getenv("PORT");
        var expectedPort = port == null ? 7070 : Integer.parseInt(port);

        assertEquals(expectedPort, App.getPort());
    }

    @Test
    void defaultDatabaseUrlIsUsed() {
        assertEquals(DEFAULT_DATABASE_URL, App.getDatabaseUrl(null));
    }

    @Test
    void databaseUrlCanBeConfigured() {
        var databaseUrl = "jdbc:h2:mem:custom;DB_CLOSE_DELAY=-1;";

        assertEquals(databaseUrl, App.getDatabaseUrl(databaseUrl));
    }

    @Test
    void databaseCanBeInitialized() throws Exception {
        App.initDatabase("jdbc:h2:mem:app-test;DB_CLOSE_DELAY=-1;");

        assertEquals(0, UrlRepository.getEntities().size());
    }

    @Test
    void databaseDriverCanBeSelected() {
        assertEquals("org.h2.Driver", App.getDriverClassName("jdbc:h2:mem:test"));
        assertEquals("org.postgresql.Driver", App.getDriverClassName("jdbc:postgresql://db:5432/postgres"));
    }

    @Test
    void applicationCanBeStarted() throws Exception {
        var app = App.startApp(0);

        try {
            assertNotNull(app);
        } finally {
            app.stop();
        }
    }

    @Test
    void mainStartsApplication() {
        assertDoesNotThrow(() -> App.main(new String[] {}));
        App.stopApp();
    }
}
