/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import io.javalin.Javalin;

public final class App {
    private static Javalin runningApp;

    private App() {
    }

    public static Javalin getApp() {
        return Javalin.create(config -> {
            config.bundledPlugins.enableDevLogging();
            config.routes.get("/", ctx -> ctx.result("Hello World"));
        });
    }

    public static void main(String[] args) {
        runningApp = startApp(getPort());
    }

    static Javalin startApp(int port) {
        var app = getApp();
        app.start(port);
        return app;
    }

    static void stopApp() {
        runningApp.stop();
        runningApp = null;
    }

    static int getPort() {
        return getPort(System.getenv("PORT"));
    }

    static int getPort(String port) {
        return port == null ? 7070 : Integer.parseInt(port);
    }
}
