/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import gg.jte.ContentType;
import gg.jte.TemplateEngine;
import gg.jte.resolve.ResourceCodeResolver;
import hexlet.code.model.Url;
import hexlet.code.model.UrlCheck;
import hexlet.code.repository.BaseRepository;
import hexlet.code.repository.UrlCheckRepository;
import hexlet.code.repository.UrlRepository;
import io.javalin.Javalin;
import io.javalin.http.Context;
import io.javalin.http.NotFoundResponse;
import io.javalin.rendering.template.JavalinJte;
import kong.unirest.core.Unirest;
import org.jsoup.Jsoup;

public final class App {
    private static final String DEFAULT_DATABASE_URL = "jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;";
    private static Javalin runningApp;

    private App() {
    }

    public static Javalin getApp() throws SQLException, IOException {
        return getApp(getDatabaseUrl());
    }

    static Javalin getApp(String jdbcUrl) throws SQLException, IOException {
        initDatabase(jdbcUrl);

        return Javalin.create(config -> {
            config.bundledPlugins.enableDevLogging();
            config.fileRenderer(new JavalinJte(createTemplateEngine()));
            config.routes.get("/", ctx -> ctx.render("index.jte", getPageData(ctx)));
            config.routes.post("/urls", App::createUrl);
            config.routes.get("/urls", App::indexUrls);
            config.routes.get("/urls/{id}", App::showUrl);
            config.routes.post("/urls/{id}/checks", App::createUrlCheck);
        });
    }

    public static void main(String[] args) throws SQLException, IOException {
        runningApp = startApp(getPort());
    }

    static Javalin startApp(int port) throws SQLException, IOException {
        var app = getApp();
        app.start(port);
        return app;
    }

    static void stopApp() {
        runningApp.stop();
        runningApp = null;
    }

    static int getPort() {
        return getPort(System.getenv("PORT"));
    }

    static int getPort(String port) {
        return port == null ? 7070 : Integer.parseInt(port);
    }

    static String getDatabaseUrl() {
        return getDatabaseUrl(System.getenv("JDBC_DATABASE_URL"));
    }

    static String getDatabaseUrl(String jdbcDatabaseUrl) {
        return jdbcDatabaseUrl == null ? DEFAULT_DATABASE_URL : jdbcDatabaseUrl;
    }

    static void initDatabase() throws SQLException, IOException {
        initDatabase(getDatabaseUrl());
    }

    static void initDatabase(String jdbcUrl) throws SQLException, IOException {
        var dataSource = buildDataSource(jdbcUrl);
        BaseRepository.dataSource = dataSource;
        executeSql(dataSource, readResourceFile("schema.sql"));
    }

    static HikariDataSource buildDataSource(String jdbcUrl) {
        var hikariConfig = new HikariConfig();
        hikariConfig.setJdbcUrl(jdbcUrl);
        hikariConfig.setDriverClassName(getDriverClassName(jdbcUrl));
        return new HikariDataSource(hikariConfig);
    }

    static String getDriverClassName(String jdbcUrl) {
        return jdbcUrl.startsWith("jdbc:postgresql:") ? "org.postgresql.Driver" : "org.h2.Driver";
    }

    static String normalizeUrl(String input) throws URISyntaxException, MalformedURLException {
        if (input == null || input.isBlank()) {
            throw new MalformedURLException("Invalid URL");
        }

        var parsedUrl = new URI(input.trim()).toURL();
        var protocol = parsedUrl.getProtocol();
        var host = parsedUrl.getHost();

        if (Objects.toString(host, "").isBlank()) {
            throw new MalformedURLException("Invalid URL");
        }

        var result = protocol + "://" + host;
        var port = parsedUrl.getPort();

        return port == -1 ? result : result + ":" + port;
    }

    private static void createUrl(Context ctx) throws SQLException {
        String normalizedName;

        try {
            normalizedName = normalizeUrl(ctx.formParam("url"));
        } catch (IllegalArgumentException | MalformedURLException | URISyntaxException exception) {
            ctx.status(422).render(
                    "index.jte",
                    getPageData("Некорректный URL", "alert alert-danger")
            );
            return;
        }

        var existingUrl = UrlRepository.findByName(normalizedName);
        if (existingUrl.isPresent()) {
            var url = existingUrl.get();
            setFlash(ctx, "Страница уже существует", "alert alert-info");
            ctx.redirect("/urls/" + url.getId());
            return;
        }

        var url = new Url(normalizedName);
        UrlRepository.save(url);
        setFlash(ctx, "Страница успешно добавлена", "alert alert-success");
        ctx.redirect("/urls/" + url.getId());
    }

    private static void indexUrls(Context ctx) throws SQLException {
        var urls = UrlRepository.getEntities();
        var latestCheckDates = new HashMap<Long, String>();
        var latestCheckStatusCodes = new HashMap<Long, String>();

        for (var url : urls) {
            var latestCheck = UrlCheckRepository.findLatestByUrlId(url.getId());
            latestCheck.ifPresent(check -> {
                latestCheckDates.put(url.getId(), check.getCreatedAtAsDate());
                latestCheckStatusCodes.put(url.getId(), String.valueOf(check.getStatusCode()));
            });
        }

        var pageData = getPageData(ctx);
        pageData.put("urls", urls);
        pageData.put("latestCheckDates", latestCheckDates);
        pageData.put("latestCheckStatusCodes", latestCheckStatusCodes);
        ctx.render("urls/index.jte", pageData);
    }

    private static void showUrl(Context ctx) throws SQLException {
        var id = Long.valueOf(ctx.pathParam("id"));
        var url = UrlRepository.find(id)
                .orElseThrow(() -> new NotFoundResponse("Url not found"));

        var pageData = getPageData(ctx);
        pageData.put("url", url);
        pageData.put("checks", UrlCheckRepository.findByUrlId(id));
        ctx.render("urls/show.jte", pageData);
    }

    private static void createUrlCheck(Context ctx) throws SQLException {
        var id = Long.valueOf(ctx.pathParam("id"));
        var url = UrlRepository.find(id)
                .orElseThrow(() -> new NotFoundResponse("Url not found"));

        try {
            var urlCheck = checkUrl(url);
            UrlCheckRepository.save(urlCheck);
            setFlash(ctx, "Страница успешно проверена", "alert alert-success");
        } catch (RuntimeException exception) {
            setFlash(ctx, "Произошла ошибка при проверке", "alert alert-danger");
        }

        ctx.redirect("/urls/" + id);
    }

    private static UrlCheck checkUrl(Url url) {
        var response = Unirest.get(url.getName()).asString();

        if (response.getStatus() >= 400) {
            throw new IllegalStateException("URL check failed with status " + response.getStatus());
        }

        var body = Objects.toString(response.getBody(), "");
        var document = Jsoup.parse(body);
        var h1Element = document.selectFirst("h1");
        var h1 = h1Element == null ? "" : h1Element.text();
        var descriptionElement = document.selectFirst("meta[name=description]");
        var description = descriptionElement == null ? "" : descriptionElement.attr("content");

        return new UrlCheck(url.getId(), response.getStatus(), h1, document.title(), description);
    }

    private static Map<String, Object> getPageData(Context ctx) {
        var pageData = new HashMap<String, Object>();
        pageData.put("flash", ctx.consumeSessionAttribute("flash"));
        pageData.put("flashClass", ctx.consumeSessionAttribute("flashClass"));
        return pageData;
    }

    private static Map<String, Object> getPageData(String flash, String flashClass) {
        var pageData = new HashMap<String, Object>();
        pageData.put("flash", flash);
        pageData.put("flashClass", flashClass);
        return pageData;
    }

    private static void setFlash(Context ctx, String flash, String flashClass) {
        ctx.sessionAttribute("flash", flash);
        ctx.sessionAttribute("flashClass", flashClass);
    }

    private static TemplateEngine createTemplateEngine() {
        ClassLoader classLoader = App.class.getClassLoader();
        ResourceCodeResolver codeResolver = new ResourceCodeResolver("templates", classLoader);
        return TemplateEngine.create(codeResolver, ContentType.Html);
    }

    private static void executeSql(HikariDataSource dataSource, String sql) throws SQLException {
        try (var connection = dataSource.getConnection();
                var statement = connection.createStatement()) {
            for (var sqlStatement : sql.split(";")) {
                var trimmedSqlStatement = sqlStatement.trim();
                if (!trimmedSqlStatement.isEmpty()) {
                    statement.execute(trimmedSqlStatement);
                }
            }
        }
    }

    private static String readResourceFile(String fileName) throws IOException {
        var inputStream = Objects.requireNonNull(App.class.getClassLoader().getResourceAsStream(fileName));
        try (var reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8))) {
            return reader.lines().collect(Collectors.joining("\n"));
        }
    }
}
