/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    checkstyle
    jacoco
    id("org.sonarqube") version "7.3.1.8318"
    id("com.gradleup.shadow") version "9.6.0"
}

group = "hexlet.code"
version = "1.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("io.javalin:javalin:7.2.2")
    implementation("io.javalin:javalin-rendering-jte:7.2.2")
    implementation("gg.jte:jte:3.2.0")
    implementation("org.slf4j:slf4j-simple:2.0.18")
    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("com.h2database:h2:2.4.240")
    implementation("org.postgresql:postgresql:42.7.11")
    implementation(platform("com.konghq:unirest-java-bom:4.5.1"))
    implementation("com.konghq:unirest-java-core")
    implementation("org.jsoup:jsoup:1.22.2")

    testImplementation("io.javalin:javalin-testtools:7.2.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "hexlet.code.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    environment("PORT", "0")
    environment("JDBC_DATABASE_URL", "jdbc:h2:mem:gradle_test;DB_CLOSE_DELAY=-1;")
}




sonar {
    properties {
        property("sonar.projectKey", "bedrevpaul23_java-project-72")
        property("sonar.organization", "bedrevpaul23")
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml")
    }
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)

    classDirectories.setFrom(files(classDirectories.files.map {
        fileTree(it) {
            exclude("hexlet/code/repository/*.class")
        }
    }))

    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

tasks.named("sonar") {
    dependsOn(tasks.jacocoTestReport)
}
